
export const categoriesStyle = {
    'Breakfast': { color: '#CFDDDB', hover: '#B8C9C7', icon: 'Coffee' },
    'Soups': { color: '#E4CDED', hover: '#D1B5DB', icon: 'Soup' },
    'Pasta': { color: '#C2DBE9', hover: '#A9C7D9', icon: 'CookingPot' },
    'Sushi': { color: '#C9CAEF', hover: '#B1B2DB', icon: 'Fish' },
    'Main course': { color: '#FAC1D9', hover: '#E8A9C2', icon: 'Utensils' },
    'Desserts': { color: '#E5DADE', hover: '#CDC1C5', icon: 'CakeSlice' },
    'Pizza': { color: '#FDE2E4', hover: '#E9C8CB', icon: 'Pizza' },
    'Burgers': { color: '#FFF1E6', hover: '#E9D9CD', icon: 'Beef' },
    'Salads': { color: '#DFF3E3', hover: '#C8E4CD', icon: 'Leaf' },
    'Bakery': { color: '#F8EDEB', hover: '#F1D5D0', icon: 'Croissant' },
    'Seafood': { color: '#E0FBFC', hover: '#C2E7E9', icon: 'Shellfish' },
    'Mexican': { color: '#F1E3D3', hover: '#E2CDBA', icon: 'Taco' },
    'Traditional': { color: '#C2E9DD', hover: '#A9D6C8', icon: 'ChefHat' },

    'Drinks': { color: '#F1C8D0', hover: '#DBB1B9', icon: 'GlassWater' },
    'Coffee Bar': { color: '#DDB892', hover: '#B08968', icon: 'Bean' },
    'Wine': { color: '#FFD1DC', hover: '#FFB7C5', icon: 'GlassWine' },
    'Beer': { color: '#E9EDC9', hover: '#CCD5AE', icon: 'Beer' },
    'Snacks': { color: '#FEFAE0', hover: '#F4F1BB', icon: 'Cookie' },
    'Ice Cream': { color: '#FAD2E1', hover: '#F8BBD0', icon: 'IceCream' },

    'Fine Dining': { color: '#E5E5E5', hover: '#D4D4D4', icon: 'UtensilsCrossed' },
    'Sweets': { color: '#F3E5F5', hover: '#E1BEE7', icon: 'Candy' },
    'Seasonal': { color: '#FFEBEE', hover: '#FFCDD2', icon: 'CandyCane' },
    'Sandwiches': { color: '#FFF9C4', hover: '#FFF59D', icon: 'Sandwich' },
    'Eggs': { color: '#FFFFFF', hover: '#F5F5F5', icon: 'Egg' },
    'Brunch': { color: '#FFFDE7', hover: '#FFF9C4', icon: 'EggFried' },
    'Meat': { color: '#FFEBEE', hover: '#FFCDD2', icon: 'Ham' },
    'Poultry': { color: '#FFF8E1', hover: '#FFECB3', icon: 'Drumstick' },
    'Tex-Mex': { color: '#FBE9E7', hover: '#FFCCBC', icon: 'Burrito' },
    'Pastries': { color: '#FCE4EC', hover: '#F8BBD0', icon: 'Donut' },
    'Vegetables': { color: '#F1F8E9', hover: '#DCEDC8', icon: 'Corn' },
    'Citrus': { color: '#FFFDE7', hover: '#FFF9C4', icon: 'Citrus' },
    'Berries': { color: '#FFEBEE', hover: '#FFCDD2', icon: 'Strawberry' },
    'Fruits': { color: '#FFF3E0', hover: '#FFE0B2', icon: 'Apple' },
    'Tropical': { color: '#FFFDE7', hover: '#FFF59D', icon: 'Banana' },
    'Cherries': { color: '#FFEBEE', hover: '#FFCDD2', icon: 'Cherry' },
    'Grapes': { color: '#F3E5F5', hover: '#E1BEE7', icon: 'Grape' },
    'Nuts': { color: '#EFEBE9', hover: '#D7CCC8', icon: 'Nut' },
    'Mushrooms': { color: '#F5F5F5', hover: '#EEEEEE', icon: 'Mushroom' },
    'Pickles': { color: '#E8F5E9', hover: '#C8E6C9', icon: 'Pickle' },
    'Grains': { color: '#FFF8E1', hover: '#FFECB3', icon: 'Wheat' },
    'Gluten-Free': { color: '#FAFAFA', hover: '#F5F5F5', icon: 'WheatOff' },
    'Popcorn': { color: '#FFFDE7', hover: '#FFF9C4', icon: 'Popcorn' },
    'BBQ': { color: '#FFEBEE', hover: '#FFCDD2', icon: 'FlameKindling' },

    'Soda': { color: '#E0F2F1', hover: '#B2DFDB', icon: 'CupSoda' },
    'Non-Alcoholic': { color: '#F5F5F5', hover: '#EEEEEE', icon: 'BeerOff' },
    'Dairy': { color: '#FFFFFF', hover: '#F5F5F5', icon: 'Milk' },
    'Alcohol-Free Wine': { color: '#FAFAFA', hover: '#F5F5F5', icon: 'WineOff' },
    'Red Wine': { color: '#FCE4EC', hover: '#F8BBD0', icon: 'Wine' },
    'Hot Drinks': { color: '#EFEBE9', hover: '#D7CCC8', icon: 'Mug' },
    'Beverages': { color: '#F5F5F5', hover: '#E0E0E0', icon: 'Cup' },
    'Bottled': { color: '#E0F2F1', hover: '#B2DFDB', icon: 'Bottle' },
    'Cocktails': { color: '#E0F7FA', hover: '#B2EBF2', icon: 'Cocktail' },
    'Lounge': { color: '#F3E5F5', hover: '#E1BEE7', icon: 'Martini' },
    'Brewery': { color: '#E8F5E9', hover: '#C8E6C9', icon: 'Hop' },

    'Cold Storage': { color: '#E0F2F1', hover: '#B2DFDB', icon: 'Refrigerator' },
    'Quick Heat': { color: '#ECEFF1', hover: '#CFD8DC', icon: 'Microwave' },
    'Dining': { color: '#F5F5F5', hover: '#E0E0E0', icon: 'ForkKnife' },
    'Service': { color: '#E3F2FD', hover: '#BBDEFB', icon: 'HandPlatter' },
    'Organic': { color: '#E8F5E9', hover: '#C8E6C9', icon: 'Sprout' },
    'Market': { color: '#F3E5F5', hover: '#E1BEE7', icon: 'Store' },

    'Appetizers': { color: '#EDF2FB', hover: '#D7E1F5', icon: 'Fingerprint' },
    'Healthy': { color: '#B7E4C7', hover: '#95D5B2', icon: 'Carrot' },
    'Vegetarian': { color: '#D8E2DC', hover: '#C4D3CB', icon: 'Vegan' },

    'default': { color: '#F3F4F6', hover: '#E5E7EB', icon: 'HelpCircle' }
};